spring:
  profiles:
    active: core, db
  message:
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  DEBUG