package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZcCategory;
import org.linlinjava.litemall.db.domain.ZcCategoryExample;

public interface ZcCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    long countByExample(ZcCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    int deleteByExample(ZcCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    int insert(ZcCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    int insertSelective(ZcCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcCategory selectOneByExample(ZcCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcCategory selectOneByExampleSelective(@Param("example") ZcCategoryExample example, @Param("selective") ZcCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZcCategory> selectByExampleSelective(@Param("example") ZcCategoryExample example, @Param("selective") ZcCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    List<ZcCategory> selectByExample(ZcCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZcCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    ZcCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZcCategory record, @Param("example") ZcCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZcCategory record, @Param("example") ZcCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZcCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZcCategory record);
}