package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZcMessage;
import org.linlinjava.litemall.db.domain.ZcMessageExample;

public interface ZcMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    long countByExample(ZcMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    int deleteByExample(ZcMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    int insert(ZcMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    int insertSelective(ZcMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcMessage selectOneByExample(ZcMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcMessage selectOneByExampleSelective(@Param("example") ZcMessageExample example, @Param("selective") ZcMessage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZcMessage> selectByExampleSelective(@Param("example") ZcMessageExample example, @Param("selective") ZcMessage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    List<ZcMessage> selectByExample(ZcMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcMessage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZcMessage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    ZcMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZcMessage record, @Param("example") ZcMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZcMessage record, @Param("example") ZcMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZcMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZcMessage record);
}