package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZcProducttype;
import org.linlinjava.litemall.db.domain.ZcProducttypeExample;

public interface ZcProducttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    long countByExample(ZcProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    int deleteByExample(ZcProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    int insert(ZcProducttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    int insertSelective(ZcProducttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcProducttype selectOneByExample(ZcProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcProducttype selectOneByExampleSelective(@Param("example") ZcProducttypeExample example, @Param("selective") ZcProducttype.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZcProducttype> selectByExampleSelective(@Param("example") ZcProducttypeExample example, @Param("selective") ZcProducttype.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    List<ZcProducttype> selectByExample(ZcProducttypeExample example);

    List<ZcProducttype> selectByPlatforms(List<String> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcProducttype selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZcProducttype.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    ZcProducttype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZcProducttype record, @Param("example") ZcProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZcProducttype record, @Param("example") ZcProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZcProducttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_producttype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZcProducttype record);
}