package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZcProduct;
import org.linlinjava.litemall.db.domain.ZcProductExample;

public interface ZcProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    long countByExample(ZcProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    int deleteByExample(ZcProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    int insert(ZcProduct record);

    /**
     * 批量插入产品
     * @param list
     * @return
     */
    int batchInsert(List<ZcProduct> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    int insertSelective(ZcProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcProduct selectOneByExample(ZcProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcProduct selectOneByExampleSelective(@Param("example") ZcProductExample example, @Param("selective") ZcProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZcProduct> selectByExampleSelective(@Param("example") ZcProductExample example, @Param("selective") ZcProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    List<ZcProduct> selectByExample(ZcProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZcProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZcProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    ZcProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZcProduct record, @Param("example") ZcProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZcProduct record, @Param("example") ZcProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZcProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZcProduct record);
}