package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class ZcProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.productnum
     *
     * @mbg.generated
     */
    private String productnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.producttype
     *
     * @mbg.generated
     */
    private String producttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.productname
     *
     * @mbg.generated
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.snapshot
     *
     * @mbg.generated
     */
    private String snapshot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.realpic
     *
     * @mbg.generated
     */
    private String realpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.structtype
     *
     * @mbg.generated
     */
    private String structtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.traintype
     *
     * @mbg.generated
     */
    private String traintype;
    private String traintypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.platform
     *
     * @mbg.generated
     */
    private String platform;
    private String platformname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.provider
     *
     * @mbg.generated
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.wj
     *
     * @mbg.generated
     */
    private String wj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.bzgd
     *
     * @mbg.generated
     */
    private String bzgd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.cz
     *
     * @mbg.generated
     */
    private String cz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.lgjzdjj
     *
     * @mbg.generated
     */
    private String lgjzdjj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.zczjj
     *
     * @mbg.generated
     */
    private String zczjj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.ngbcd
     *
     * @mbg.generated
     */
    private String ngbcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.jxhz
     *
     * @mbg.generated
     */
    private String jxhz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.plhz
     *
     * @mbg.generated
     */
    private String plhz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.xtgd
     *
     * @mbg.generated
     */
    private String xtgd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.lgzxj
     *
     * @mbg.generated
     */
    private String lgzxj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.gtqtwj
     *
     * @mbg.generated
     */
    private String gtqtwj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.klx
     *
     * @mbg.generated
     */
    private String klx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.yzl
     *
     * @mbg.generated
     */
    private String yzl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.jxgd
     *
     * @mbg.generated
     */
    private String jxgd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.cd
     *
     * @mbg.generated
     */
    private String cd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.kd
     *
     * @mbg.generated
     */
    private String kd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.gd
     *
     * @mbg.generated
     */
    private String gd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.zpcc
     *
     * @mbg.generated
     */
    private String zpcc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.zongxgd
     *
     * @mbg.generated
     */
    private String zongxgd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.zpcd
     *
     * @mbg.generated
     */
    private String zpcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.zhouxgd
     *
     * @mbg.generated
     */
    private String zhouxgd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.kz
     *
     * @mbg.generated
     */
    private String kz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.zdhz
     *
     * @mbg.generated
     */
    private String zdhz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.cxgd
     *
     * @mbg.generated
     */
    private String cxgd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.ysg
     *
     * @mbg.generated
     */
    private String ysg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.cxhz
     *
     * @mbg.generated
     */
    private String cxhz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.syhz
     *
     * @mbg.generated
     */
    private String syhz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.gangd
     *
     * @mbg.generated
     */
    private String gangd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.vxjd
     *
     * @mbg.generated
     */
    private String vxjd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.zyg
     *
     * @mbg.generated
     */
    private String zyg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_e_product.zyg
     *
     * @mbg.generated
     */
    private String hxgd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.id
     *
     * @return the value of t_e_product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.id
     *
     * @param id the value for t_e_product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.productnum
     *
     * @return the value of t_e_product.productnum
     *
     * @mbg.generated
     */
    public String getProductnum() {
        return productnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.productnum
     *
     * @param productnum the value for t_e_product.productnum
     *
     * @mbg.generated
     */
    public void setProductnum(String productnum) {
        this.productnum = productnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.producttype
     *
     * @return the value of t_e_product.producttype
     *
     * @mbg.generated
     */
    public String getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.producttype
     *
     * @param producttype the value for t_e_product.producttype
     *
     * @mbg.generated
     */
    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.productname
     *
     * @return the value of t_e_product.productname
     *
     * @mbg.generated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.productname
     *
     * @param productname the value for t_e_product.productname
     *
     * @mbg.generated
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.snapshot
     *
     * @return the value of t_e_product.snapshot
     *
     * @mbg.generated
     */
    public String getSnapshot() {
        return snapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.snapshot
     *
     * @param snapshot the value for t_e_product.snapshot
     *
     * @mbg.generated
     */
    public void setSnapshot(String snapshot) {
        this.snapshot = snapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.realpic
     *
     * @return the value of t_e_product.realpic
     *
     * @mbg.generated
     */
    public String getRealpic() {
        return realpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.realpic
     *
     * @param realpic the value for t_e_product.realpic
     *
     * @mbg.generated
     */
    public void setRealpic(String realpic) {
        this.realpic = realpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.structtype
     *
     * @return the value of t_e_product.structtype
     *
     * @mbg.generated
     */
    public String getStructtype() {
        return structtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.structtype
     *
     * @param structtype the value for t_e_product.structtype
     *
     * @mbg.generated
     */
    public void setStructtype(String structtype) {
        this.structtype = structtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.traintype
     *
     * @return the value of t_e_product.traintype
     *
     * @mbg.generated
     */
    public String getTraintype() {
        return traintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.traintype
     *
     * @param traintype the value for t_e_product.traintype
     *
     * @mbg.generated
     */
    public void setTraintype(String traintype) {
        this.traintype = traintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.remark
     *
     * @return the value of t_e_product.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.remark
     *
     * @param remark the value for t_e_product.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.platform
     *
     * @return the value of t_e_product.platform
     *
     * @mbg.generated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.platform
     *
     * @param platform the value for t_e_product.platform
     *
     * @mbg.generated
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.provider
     *
     * @return the value of t_e_product.provider
     *
     * @mbg.generated
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.provider
     *
     * @param provider the value for t_e_product.provider
     *
     * @mbg.generated
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.wj
     *
     * @return the value of t_e_product.wj
     *
     * @mbg.generated
     */
    public String getWj() {
        return wj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.wj
     *
     * @param wj the value for t_e_product.wj
     *
     * @mbg.generated
     */
    public void setWj(String wj) {
        this.wj = wj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.bzgd
     *
     * @return the value of t_e_product.bzgd
     *
     * @mbg.generated
     */
    public String getBzgd() {
        return bzgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.bzgd
     *
     * @param bzgd the value for t_e_product.bzgd
     *
     * @mbg.generated
     */
    public void setBzgd(String bzgd) {
        this.bzgd = bzgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.cz
     *
     * @return the value of t_e_product.cz
     *
     * @mbg.generated
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.cz
     *
     * @param cz the value for t_e_product.cz
     *
     * @mbg.generated
     */
    public void setCz(String cz) {
        this.cz = cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.weight
     *
     * @return the value of t_e_product.weight
     *
     * @mbg.generated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.weight
     *
     * @param weight the value for t_e_product.weight
     *
     * @mbg.generated
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.lgjzdjj
     *
     * @return the value of t_e_product.lgjzdjj
     *
     * @mbg.generated
     */
    public String getLgjzdjj() {
        return lgjzdjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.lgjzdjj
     *
     * @param lgjzdjj the value for t_e_product.lgjzdjj
     *
     * @mbg.generated
     */
    public void setLgjzdjj(String lgjzdjj) {
        this.lgjzdjj = lgjzdjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.zczjj
     *
     * @return the value of t_e_product.zczjj
     *
     * @mbg.generated
     */
    public String getZczjj() {
        return zczjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.zczjj
     *
     * @param zczjj the value for t_e_product.zczjj
     *
     * @mbg.generated
     */
    public void setZczjj(String zczjj) {
        this.zczjj = zczjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.ngbcd
     *
     * @return the value of t_e_product.ngbcd
     *
     * @mbg.generated
     */
    public String getNgbcd() {
        return ngbcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.ngbcd
     *
     * @param ngbcd the value for t_e_product.ngbcd
     *
     * @mbg.generated
     */
    public void setNgbcd(String ngbcd) {
        this.ngbcd = ngbcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.jxhz
     *
     * @return the value of t_e_product.jxhz
     *
     * @mbg.generated
     */
    public String getJxhz() {
        return jxhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.jxhz
     *
     * @param jxhz the value for t_e_product.jxhz
     *
     * @mbg.generated
     */
    public void setJxhz(String jxhz) {
        this.jxhz = jxhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.plhz
     *
     * @return the value of t_e_product.plhz
     *
     * @mbg.generated
     */
    public String getPlhz() {
        return plhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.plhz
     *
     * @param plhz the value for t_e_product.plhz
     *
     * @mbg.generated
     */
    public void setPlhz(String plhz) {
        this.plhz = plhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.xtgd
     *
     * @return the value of t_e_product.xtgd
     *
     * @mbg.generated
     */
    public String getXtgd() {
        return xtgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.xtgd
     *
     * @param xtgd the value for t_e_product.xtgd
     *
     * @mbg.generated
     */
    public void setXtgd(String xtgd) {
        this.xtgd = xtgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.lgzxj
     *
     * @return the value of t_e_product.lgzxj
     *
     * @mbg.generated
     */
    public String getLgzxj() {
        return lgzxj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.lgzxj
     *
     * @param lgzxj the value for t_e_product.lgzxj
     *
     * @mbg.generated
     */
    public void setLgzxj(String lgzxj) {
        this.lgzxj = lgzxj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.gtqtwj
     *
     * @return the value of t_e_product.gtqtwj
     *
     * @mbg.generated
     */
    public String getGtqtwj() {
        return gtqtwj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.gtqtwj
     *
     * @param gtqtwj the value for t_e_product.gtqtwj
     *
     * @mbg.generated
     */
    public void setGtqtwj(String gtqtwj) {
        this.gtqtwj = gtqtwj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.klx
     *
     * @return the value of t_e_product.klx
     *
     * @mbg.generated
     */
    public String getKlx() {
        return klx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.klx
     *
     * @param klx the value for t_e_product.klx
     *
     * @mbg.generated
     */
    public void setKlx(String klx) {
        this.klx = klx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.yzl
     *
     * @return the value of t_e_product.yzl
     *
     * @mbg.generated
     */
    public String getYzl() {
        return yzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.yzl
     *
     * @param yzl the value for t_e_product.yzl
     *
     * @mbg.generated
     */
    public void setYzl(String yzl) {
        this.yzl = yzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.jxgd
     *
     * @return the value of t_e_product.jxgd
     *
     * @mbg.generated
     */
    public String getJxgd() {
        return jxgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.jxgd
     *
     * @param jxgd the value for t_e_product.jxgd
     *
     * @mbg.generated
     */
    public void setJxgd(String jxgd) {
        this.jxgd = jxgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.cd
     *
     * @return the value of t_e_product.cd
     *
     * @mbg.generated
     */
    public String getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.cd
     *
     * @param cd the value for t_e_product.cd
     *
     * @mbg.generated
     */
    public void setCd(String cd) {
        this.cd = cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.kd
     *
     * @return the value of t_e_product.kd
     *
     * @mbg.generated
     */
    public String getKd() {
        return kd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.kd
     *
     * @param kd the value for t_e_product.kd
     *
     * @mbg.generated
     */
    public void setKd(String kd) {
        this.kd = kd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.gd
     *
     * @return the value of t_e_product.gd
     *
     * @mbg.generated
     */
    public String getGd() {
        return gd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.gd
     *
     * @param gd the value for t_e_product.gd
     *
     * @mbg.generated
     */
    public void setGd(String gd) {
        this.gd = gd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.zpcc
     *
     * @return the value of t_e_product.zpcc
     *
     * @mbg.generated
     */
    public String getZpcc() {
        return zpcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.zpcc
     *
     * @param zpcc the value for t_e_product.zpcc
     *
     * @mbg.generated
     */
    public void setZpcc(String zpcc) {
        this.zpcc = zpcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.zongxgd
     *
     * @return the value of t_e_product.zongxgd
     *
     * @mbg.generated
     */
    public String getZongxgd() {
        return zongxgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.zongxgd
     *
     * @param zongxgd the value for t_e_product.zongxgd
     *
     * @mbg.generated
     */
    public void setZongxgd(String zongxgd) {
        this.zongxgd = zongxgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.zpcd
     *
     * @return the value of t_e_product.zpcd
     *
     * @mbg.generated
     */
    public String getZpcd() {
        return zpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.zpcd
     *
     * @param zpcd the value for t_e_product.zpcd
     *
     * @mbg.generated
     */
    public void setZpcd(String zpcd) {
        this.zpcd = zpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.zhouxgd
     *
     * @return the value of t_e_product.zhouxgd
     *
     * @mbg.generated
     */
    public String getZhouxgd() {
        return zhouxgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.zhouxgd
     *
     * @param zhouxgd the value for t_e_product.zhouxgd
     *
     * @mbg.generated
     */
    public void setZhouxgd(String zhouxgd) {
        this.zhouxgd = zhouxgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.kz
     *
     * @return the value of t_e_product.kz
     *
     * @mbg.generated
     */
    public String getKz() {
        return kz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.kz
     *
     * @param kz the value for t_e_product.kz
     *
     * @mbg.generated
     */
    public void setKz(String kz) {
        this.kz = kz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.zdhz
     *
     * @return the value of t_e_product.zdhz
     *
     * @mbg.generated
     */
    public String getZdhz() {
        return zdhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.zdhz
     *
     * @param zdhz the value for t_e_product.zdhz
     *
     * @mbg.generated
     */
    public void setZdhz(String zdhz) {
        this.zdhz = zdhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.cxgd
     *
     * @return the value of t_e_product.cxgd
     *
     * @mbg.generated
     */
    public String getCxgd() {
        return cxgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.cxgd
     *
     * @param cxgd the value for t_e_product.cxgd
     *
     * @mbg.generated
     */
    public void setCxgd(String cxgd) {
        this.cxgd = cxgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.ysg
     *
     * @return the value of t_e_product.ysg
     *
     * @mbg.generated
     */
    public String getYsg() {
        return ysg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.ysg
     *
     * @param ysg the value for t_e_product.ysg
     *
     * @mbg.generated
     */
    public void setYsg(String ysg) {
        this.ysg = ysg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.cxhz
     *
     * @return the value of t_e_product.cxhz
     *
     * @mbg.generated
     */
    public String getCxhz() {
        return cxhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.cxhz
     *
     * @param cxhz the value for t_e_product.cxhz
     *
     * @mbg.generated
     */
    public void setCxhz(String cxhz) {
        this.cxhz = cxhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.syhz
     *
     * @return the value of t_e_product.syhz
     *
     * @mbg.generated
     */
    public String getSyhz() {
        return syhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.syhz
     *
     * @param syhz the value for t_e_product.syhz
     *
     * @mbg.generated
     */
    public void setSyhz(String syhz) {
        this.syhz = syhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.gangd
     *
     * @return the value of t_e_product.gangd
     *
     * @mbg.generated
     */
    public String getGangd() {
        return gangd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.gangd
     *
     * @param gangd the value for t_e_product.gangd
     *
     * @mbg.generated
     */
    public void setGangd(String gangd) {
        this.gangd = gangd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.vxjd
     *
     * @return the value of t_e_product.vxjd
     *
     * @mbg.generated
     */
    public String getVxjd() {
        return vxjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.vxjd
     *
     * @param vxjd the value for t_e_product.vxjd
     *
     * @mbg.generated
     */
    public void setVxjd(String vxjd) {
        this.vxjd = vxjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_e_product.zyg
     *
     * @return the value of t_e_product.zyg
     *
     * @mbg.generated
     */
    public String getZyg() {
        return zyg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_e_product.zyg
     *
     * @param zyg the value for t_e_product.zyg
     *
     * @mbg.generated
     */
    public void setZyg(String zyg) {
        this.zyg = zyg;
    }

    public String getHxgd() {
        return hxgd;
    }

    public void setHxgd(String hxgd) {
        this.hxgd = hxgd;
    }

    public String getTraintypename() {
        return traintypename;
    }

    public void setTraintypename(String traintypename) {
        this.traintypename = traintypename;
    }

    public String getPlatformname() {
        return platformname;
    }

    public void setPlatformname(String platformname) {
        this.platformname = platformname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productnum=").append(productnum);
        sb.append(", producttype=").append(producttype);
        sb.append(", productname=").append(productname);
        sb.append(", snapshot=").append(snapshot);
        sb.append(", realpic=").append(realpic);
        sb.append(", structtype=").append(structtype);
        sb.append(", traintype=").append(traintype);
        sb.append(", remark=").append(remark);
        sb.append(", platform=").append(platform);
        sb.append(", provider=").append(provider);
        sb.append(", wj=").append(wj);
        sb.append(", bzgd=").append(bzgd);
        sb.append(", cz=").append(cz);
        sb.append(", weight=").append(weight);
        sb.append(", lgjzdjj=").append(lgjzdjj);
        sb.append(", zczjj=").append(zczjj);
        sb.append(", ngbcd=").append(ngbcd);
        sb.append(", jxhz=").append(jxhz);
        sb.append(", plhz=").append(plhz);
        sb.append(", xtgd=").append(xtgd);
        sb.append(", lgzxj=").append(lgzxj);
        sb.append(", gtqtwj=").append(gtqtwj);
        sb.append(", klx=").append(klx);
        sb.append(", yzl=").append(yzl);
        sb.append(", jxgd=").append(jxgd);
        sb.append(", cd=").append(cd);
        sb.append(", kd=").append(kd);
        sb.append(", gd=").append(gd);
        sb.append(", zpcc=").append(zpcc);
        sb.append(", zongxgd=").append(zongxgd);
        sb.append(", zpcd=").append(zpcd);
        sb.append(", zhouxgd=").append(zhouxgd);
        sb.append(", kz=").append(kz);
        sb.append(", zdhz=").append(zdhz);
        sb.append(", cxgd=").append(cxgd);
        sb.append(", ysg=").append(ysg);
        sb.append(", cxhz=").append(cxhz);
        sb.append(", syhz=").append(syhz);
        sb.append(", gangd=").append(gangd);
        sb.append(", vxjd=").append(vxjd);
        sb.append(", zyg=").append(zyg);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ZcProduct other = (ZcProduct) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductnum() == null ? other.getProductnum() == null : this.getProductnum().equals(other.getProductnum()))
            && (this.getProducttype() == null ? other.getProducttype() == null : this.getProducttype().equals(other.getProducttype()))
            && (this.getProductname() == null ? other.getProductname() == null : this.getProductname().equals(other.getProductname()))
            && (this.getSnapshot() == null ? other.getSnapshot() == null : this.getSnapshot().equals(other.getSnapshot()))
            && (this.getRealpic() == null ? other.getRealpic() == null : this.getRealpic().equals(other.getRealpic()))
            && (this.getStructtype() == null ? other.getStructtype() == null : this.getStructtype().equals(other.getStructtype()))
            && (this.getTraintype() == null ? other.getTraintype() == null : this.getTraintype().equals(other.getTraintype()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getPlatform() == null ? other.getPlatform() == null : this.getPlatform().equals(other.getPlatform()))
            && (this.getProvider() == null ? other.getProvider() == null : this.getProvider().equals(other.getProvider()))
            && (this.getWj() == null ? other.getWj() == null : this.getWj().equals(other.getWj()))
            && (this.getBzgd() == null ? other.getBzgd() == null : this.getBzgd().equals(other.getBzgd()))
            && (this.getCz() == null ? other.getCz() == null : this.getCz().equals(other.getCz()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getLgjzdjj() == null ? other.getLgjzdjj() == null : this.getLgjzdjj().equals(other.getLgjzdjj()))
            && (this.getZczjj() == null ? other.getZczjj() == null : this.getZczjj().equals(other.getZczjj()))
            && (this.getNgbcd() == null ? other.getNgbcd() == null : this.getNgbcd().equals(other.getNgbcd()))
            && (this.getJxhz() == null ? other.getJxhz() == null : this.getJxhz().equals(other.getJxhz()))
            && (this.getPlhz() == null ? other.getPlhz() == null : this.getPlhz().equals(other.getPlhz()))
            && (this.getXtgd() == null ? other.getXtgd() == null : this.getXtgd().equals(other.getXtgd()))
            && (this.getLgzxj() == null ? other.getLgzxj() == null : this.getLgzxj().equals(other.getLgzxj()))
            && (this.getGtqtwj() == null ? other.getGtqtwj() == null : this.getGtqtwj().equals(other.getGtqtwj()))
            && (this.getKlx() == null ? other.getKlx() == null : this.getKlx().equals(other.getKlx()))
            && (this.getYzl() == null ? other.getYzl() == null : this.getYzl().equals(other.getYzl()))
            && (this.getJxgd() == null ? other.getJxgd() == null : this.getJxgd().equals(other.getJxgd()))
            && (this.getCd() == null ? other.getCd() == null : this.getCd().equals(other.getCd()))
            && (this.getKd() == null ? other.getKd() == null : this.getKd().equals(other.getKd()))
            && (this.getGd() == null ? other.getGd() == null : this.getGd().equals(other.getGd()))
            && (this.getZpcc() == null ? other.getZpcc() == null : this.getZpcc().equals(other.getZpcc()))
            && (this.getZongxgd() == null ? other.getZongxgd() == null : this.getZongxgd().equals(other.getZongxgd()))
            && (this.getZpcd() == null ? other.getZpcd() == null : this.getZpcd().equals(other.getZpcd()))
            && (this.getZhouxgd() == null ? other.getZhouxgd() == null : this.getZhouxgd().equals(other.getZhouxgd()))
            && (this.getKz() == null ? other.getKz() == null : this.getKz().equals(other.getKz()))
            && (this.getZdhz() == null ? other.getZdhz() == null : this.getZdhz().equals(other.getZdhz()))
            && (this.getCxgd() == null ? other.getCxgd() == null : this.getCxgd().equals(other.getCxgd()))
            && (this.getYsg() == null ? other.getYsg() == null : this.getYsg().equals(other.getYsg()))
            && (this.getCxhz() == null ? other.getCxhz() == null : this.getCxhz().equals(other.getCxhz()))
            && (this.getSyhz() == null ? other.getSyhz() == null : this.getSyhz().equals(other.getSyhz()))
            && (this.getGangd() == null ? other.getGangd() == null : this.getGangd().equals(other.getGangd()))
            && (this.getVxjd() == null ? other.getVxjd() == null : this.getVxjd().equals(other.getVxjd()))
            && (this.getZyg() == null ? other.getZyg() == null : this.getZyg().equals(other.getZyg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_e_product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductnum() == null) ? 0 : getProductnum().hashCode());
        result = prime * result + ((getProducttype() == null) ? 0 : getProducttype().hashCode());
        result = prime * result + ((getProductname() == null) ? 0 : getProductname().hashCode());
        result = prime * result + ((getSnapshot() == null) ? 0 : getSnapshot().hashCode());
        result = prime * result + ((getRealpic() == null) ? 0 : getRealpic().hashCode());
        result = prime * result + ((getStructtype() == null) ? 0 : getStructtype().hashCode());
        result = prime * result + ((getTraintype() == null) ? 0 : getTraintype().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getPlatform() == null) ? 0 : getPlatform().hashCode());
        result = prime * result + ((getProvider() == null) ? 0 : getProvider().hashCode());
        result = prime * result + ((getWj() == null) ? 0 : getWj().hashCode());
        result = prime * result + ((getBzgd() == null) ? 0 : getBzgd().hashCode());
        result = prime * result + ((getCz() == null) ? 0 : getCz().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getLgjzdjj() == null) ? 0 : getLgjzdjj().hashCode());
        result = prime * result + ((getZczjj() == null) ? 0 : getZczjj().hashCode());
        result = prime * result + ((getNgbcd() == null) ? 0 : getNgbcd().hashCode());
        result = prime * result + ((getJxhz() == null) ? 0 : getJxhz().hashCode());
        result = prime * result + ((getPlhz() == null) ? 0 : getPlhz().hashCode());
        result = prime * result + ((getXtgd() == null) ? 0 : getXtgd().hashCode());
        result = prime * result + ((getLgzxj() == null) ? 0 : getLgzxj().hashCode());
        result = prime * result + ((getGtqtwj() == null) ? 0 : getGtqtwj().hashCode());
        result = prime * result + ((getKlx() == null) ? 0 : getKlx().hashCode());
        result = prime * result + ((getYzl() == null) ? 0 : getYzl().hashCode());
        result = prime * result + ((getJxgd() == null) ? 0 : getJxgd().hashCode());
        result = prime * result + ((getCd() == null) ? 0 : getCd().hashCode());
        result = prime * result + ((getKd() == null) ? 0 : getKd().hashCode());
        result = prime * result + ((getGd() == null) ? 0 : getGd().hashCode());
        result = prime * result + ((getZpcc() == null) ? 0 : getZpcc().hashCode());
        result = prime * result + ((getZongxgd() == null) ? 0 : getZongxgd().hashCode());
        result = prime * result + ((getZpcd() == null) ? 0 : getZpcd().hashCode());
        result = prime * result + ((getZhouxgd() == null) ? 0 : getZhouxgd().hashCode());
        result = prime * result + ((getKz() == null) ? 0 : getKz().hashCode());
        result = prime * result + ((getZdhz() == null) ? 0 : getZdhz().hashCode());
        result = prime * result + ((getCxgd() == null) ? 0 : getCxgd().hashCode());
        result = prime * result + ((getYsg() == null) ? 0 : getYsg().hashCode());
        result = prime * result + ((getCxhz() == null) ? 0 : getCxhz().hashCode());
        result = prime * result + ((getSyhz() == null) ? 0 : getSyhz().hashCode());
        result = prime * result + ((getGangd() == null) ? 0 : getGangd().hashCode());
        result = prime * result + ((getVxjd() == null) ? 0 : getVxjd().hashCode());
        result = prime * result + ((getZyg() == null) ? 0 : getZyg().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_e_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        productnum("productnum", "productnum", "VARCHAR", false),
        producttype("producttype", "producttype", "VARCHAR", false),
        productname("productname", "productname", "VARCHAR", false),
        snapshot("snapshot", "snapshot", "VARCHAR", false),
        realpic("realpic", "realpic", "VARCHAR", false),
        structtype("structtype", "structtype", "VARCHAR", false),
        traintype("traintype", "traintype", "VARCHAR", false),
        remark("remark", "remark", "VARCHAR", false),
        platform("platform", "platform", "VARCHAR", false),
        provider("provider", "provider", "VARCHAR", false),
        wj("wj", "wj", "VARCHAR", false),
        bzgd("bzgd", "bzgd", "VARCHAR", false),
        cz("cz", "cz", "VARCHAR", false),
        weight("weight", "weight", "VARCHAR", false),
        lgjzdjj("lgjzdjj", "lgjzdjj", "VARCHAR", false),
        zczjj("zczjj", "zczjj", "VARCHAR", false),
        ngbcd("ngbcd", "ngbcd", "VARCHAR", false),
        jxhz("jxhz", "jxhz", "VARCHAR", false),
        plhz("plhz", "plhz", "VARCHAR", false),
        xtgd("xtgd", "xtgd", "VARCHAR", false),
        lgzxj("lgzxj", "lgzxj", "VARCHAR", false),
        gtqtwj("gtqtwj", "gtqtwj", "VARCHAR", false),
        klx("klx", "klx", "VARCHAR", false),
        yzl("yzl", "yzl", "VARCHAR", false),
        jxgd("jxgd", "jxgd", "VARCHAR", false),
        cd("cd", "cd", "VARCHAR", false),
        kd("kd", "kd", "VARCHAR", false),
        gd("gd", "gd", "VARCHAR", false),
        zpcc("zpcc", "zpcc", "VARCHAR", false),
        zongxgd("zongxgd", "zongxgd", "VARCHAR", false),
        zpcd("zpcd", "zpcd", "VARCHAR", false),
        zhouxgd("zhouxgd", "zhouxgd", "VARCHAR", false),
        kz("kz", "kz", "VARCHAR", false),
        zdhz("zdhz", "zdhz", "VARCHAR", false),
        cxgd("cxgd", "cxgd", "VARCHAR", false),
        ysg("ysg", "ysg", "VARCHAR", false),
        cxhz("cxhz", "cxhz", "VARCHAR", false),
        syhz("syhz", "syhz", "VARCHAR", false),
        gangd("gangd", "gangd", "VARCHAR", false),
        vxjd("vxjd", "vxjd", "VARCHAR", false),
        zyg("zyg", "zyg", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_e_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}