spring:
  profiles:
    active: db, core, admin, wx
  message:
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  ERROR
    org.linlinjava.litemall.db:  ERROR
    org.linlinjava.litemall.admin:  ERROR
    org.linlinjava.litemall.wx:  ERROR
    org.linlinjava.litemall:  ERROR